server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    ROOT: info
    com.netflix.eureka: off
    com.netflix.discovery: off

---
# For development in docker container
spring:
  profiles: docker
