sudo: enabled

language: java
jdk:
  - openjdk8

services:
  - docker

install:
  - make init
  - REPO_DIR=`pwd`
  - echo "CODE_PATH=${REPO_DIR}" > .env
  - cat .env
  - make env-up

scripts:
  - netstat -lntp
  - docker ps
  - make test
  #- make env-down
