language: java

services:
  - docker

jdk:
  - openjdk8

env:
  - DOCKER_COMPOSE_VERSION=1.21.0

before_script:
# - sudo redis-server /etc/redis/redis.conf --requirepass 'password'
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/release/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d
  - ./gradlew bootJar
  - ./wait-for 127.0.0.1:5432 -t 1000 -- echo 'postgres up'
  - ./wait-for 127.0.0.1:6379 -t 1000 -- echo 'redis up'
