os: linux
dist: xenial

language: java
jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
  - stage: unit-tests
    before_install:
      - REPO_DIR=`pwd`
      - echo "POSTGRES_TAG=11.5-alpine" > $REPO_DIR/.env
      - echo "REDIS_TAG=5.0.8-alpine" > $REPO_DIR/.env
      - echo "CONSUL_TAG=1.7.3" > $REPO_DIR/.env
      - echo "KEYCLOAK_TAG=8.0.0" > $REPO_DIR/.env
      - echo "RABBITMQ_TAG=3-management" > $REPO_DIR/.env
      - echo "CUBIC_TAG=latest" > $REPO_DIR/.env
      - echo "CODE_PATH=$REPO_DIR" > $REPO_DIR/.env
    install:
      - make init
      - make env-up
    script:
      - make unit-test
    after_script:
      - make env-down
      - make prune

  - stage: test
    before_install:
      - REPO_DIR=`pwd`
      - echo "CODE_PATH=$REPO_DIR" > $REPO_DIR/.env
    install:
      - make image
      - make images
      - make init
      - make standalone-up
      # with 5 minutes of timeout: if timeout is reached, it exits with error(1)
      - timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9990/auth/admin/master/console/)" != "200" ]]; do sleep 5 && echo "wait for keycloak"; done' || false
      - timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/actuator/health)" != "200" ]]; do sleep 5 && echo "wait for gateway"; done' || false
    script:
      - make test
    after_script:
      - make standalone-down
      - make prune

  - stage: publish
    if: tag IS present
    install:
      - make image
      - make images
    script:
      - version=$(git describe --tags `git rev-list --tags --max-count=1`)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - TAG_VERSION=$version make publish-images
      - TAG_VERSION=$version make prune-images
