sudo: enabled

language: java
jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
  - stage: unit-tests
    install:
    - REPO_DIR=`pwd`
    - echo "CODE_PATH=$REPO_DIR" > $REPO_DIR/.env
    - make init
    - make env-up
    scripts:
    - make vet
    - make unit-test
    - make env-down
    - make prune

  - stage: integration-tests
    install:
      - REPO_DIR=`pwd`
      - echo "CODE_PATH=$REPO_DIR" > $REPO_DIR/.env
      - make image
      - make images
      - make init
      - make standalone-up
    scripts:
      - make integration-test
      - make standalone-down
      - make prune
