sudo: enabled

language: java
jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
    - stage: tests
      script:
        - make init
        - make env-up
        - make test
        - make env-down
