os: linux
dist: xenial

language: java
jdk:
  - openjdk8

services:
  - docker

jobs:
  include:
  - stage: unit-tests
    install:
    - REPO_DIR=`pwd`
    - echo "CODE_PATH=$REPO_DIR" > $REPO_DIR/.env
    - make init
    - make env-up
    script:
    - make vet
    - make unit-test
    - make env-down
    - make prune

  - stage: integration-tests
    install:
      - REPO_DIR=`pwd`
      - echo "CODE_PATH=$REPO_DIR" > $REPO_DIR/.env
      - make image
      - make images
      - make init
      - make env-up
      - make env-down
      - make standalone-up
      - ./wait-for localhost:8761 -t 1000 -- echo 'discovery-service is up'
      - ./wait-for localhost:9990 -t 1000 -- echo 'keycloak http is up'
      - ./wait-for localhost:9991 -t 1000 -- echo 'keycloak https is up'
      - ./wait-for localhost:8080 -t 1000 -- echo 'gateway is up'
    script:
      # with 5 minutes of timeout: if timeout is reached, it exits with error(1)
      - timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/actuator/health)" != "200" ]]; do sleep 5; done' || false
      - make integration-test
      - make standalone-down
      - make prune
