version: '3.5'
services:

  consul-server-1: &consul-server
    image: consul:latest
    networks:
      - consul-net
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-server
    ports:
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consul-net:
