version: '3.5'
services:
  postgres:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - postgres_database:/var/lib/postgresql/data
      - "${CODE_PATH}/data/postgres-entrypoint:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Shanghai
  redis:
    image: redis:5.0.8-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_database:/data
      - "${CODE_PATH}/data/redis-entrypoint/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
  consul-server-1: &consul-server
    image: consul:1.7.3
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
  consul-server-2:
    <<: *consul-server
  consul-server-bootstrap:
    <<: *consul-server
    ports:
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
  keycloak:
    image: jboss/keycloak:8.0.0
    volumes:
      - "${CODE_PATH}/data/keycloak/ultrasound-realm.json:/tmp/ultrasound-realm.json"
    ports:
      - 9990:8080
      - 9991:8443
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=oauth2_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/ultrasound-realm.json
      - TZ=Asia/Shanghai
    depends_on:
      - postgres

volumes:
  postgres_database:
    external: true
  redis_database:
    external: true
