version: '3.5'
services:
  postgres:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_PATH}/postgres:/var/lib/postgresql/data"
      - "${CODE_PATH}/data/postgres-entrypoint:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Shanghai
  redis:
    image: redis:5.0.8-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DATA_PATH}/redis:/data"
      - "${CODE_PATH}/data/redis-entrypoint/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
#  uaa:
#    image: apm/uaa:latest
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#    ports:
#      - "8090:8090"
#    environment:
#      - TZ=Asia/Shanghai
