server:
  port: ${SERVER_PORT:0}

media-server:
  base-url: ${MEDIA_SERVER_URL:http://localhost:9001}
  username: ${MEDIA_SERVER_USERNAME:admin}
  password: ${MEDIA_SERVER_PASSWORD:password}

spring:
  application:
    name: smh-service

---
# For development in docker container
spring:
  profiles: docker
