server:
  port: 0
  servlet:
    context-path: /chat

channel:
  broadcast: websocket.broadcast
  userStatus: websocket.userStatus

status:
  onlineUserKey: onlineUsers

spring:
  application:
    name: chat-api-service
  redis:
    database: 1
    host: localhost
    port: 6379
    password: password
    timeout: 2000
    ssl: false
    jedis:
      pool:
        max-active: 10
        max-wait: 5000ms
        max-idle: 8
        min-idle: 2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
