server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /

customized:
  redis-key:
    online-user: onlineUsers

keycloak:
  realm: ultrasound
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:9990/auth}
  ssl-required: external
  resource: chat_api_service
  credentials:
    secret: fad16a55-6b53-4c4f-8919-aeffe428752f
  use-resource-role-mappings: true
  bearer-only: true

spring:
  application:
    name: chat-api-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: cubic
    password: password
  redis:
    database: 1
    host: ${REDIS_SERVER_HOST:localhost}
    port: 6379
    password: password
    timeout: 2000
    ssl: false
    jedis:
      pool:
        max-active: 10
        max-wait: 5000ms
        max-idle: 8
        min-idle: 2

---
# For development in docker container
spring:
  profiles: docker
