server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /

channel:
  broadcast: websocket.broadcast
  userStatus: websocket.userStatus

status:
  onlineUserKey: onlineUsers

spring:
  application:
    name: chat-api-service
  redis:
    database: 1
    host: ${REDIS_SERVER_HOST:localhost}
    port: 6379
    password: password
    timeout: 2000
    ssl: false
    jedis:
      pool:
        max-active: 10
        max-wait: 5000ms
        max-idle: 8
        min-idle: 2

---
# For development in docker container
spring:
  profiles: docker
