server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /ultrasound

keycloak:
  realm: ultrasound
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:9990/auth}
  ssl-required: external
  resource: ultrasound_api_service
  credentials:
    secret: 4b63963a-c21a-47aa-8abd-68997389234d
  use-resource-role-mappings: true
  bearer-only: true

spring:
  application:
    name: ultrasound-api-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    ROOT: info
    com.github.dantin: debug

---
# For development in docker container
spring:
  profiles: docker
