server:
  port: 10001
  servlet:
    context-path: /ultrasound

keycloak:
  realm: ultrasound
  auth-server-url: http://localhost:8083/auth
  ssl-required: external
  resource: ultrasound_api_service
  credentials:
    secret: 3d973f0c-d0ed-43b9-8c13-67f5ea73e335
  use-resource-role-mappings: true
  bearer-only: true

spring:
  application:
    name: ultrasound-api-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    ROOT: info
