server:
  port: ${SERVER_PORT:0}
  servlet:
    context-path: /

keycloak:
  realm: ultrasound
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:9990/auth}
  ssl-required: external
  resource: ultrasound_api_service
  credentials:
    secret: 4b63963a-c21a-47aa-8abd-68997389234d
  use-resource-role-mappings: true
  bearer-only: true

spring:
  application:
    name: ultrasound-api-service
  redis:
    database: 1
    host: ${REDIS_SERVER_HOST:localhost}
    port: 6379
    password: password
    timeout: 2000
    ssl: false
    jedis:
      pool:
        max-active: 10
        max-wait: 5000ms
        max-idle: 8
        min-idle: 2

logging:
  level:
    ROOT: info
    com.github.dantin: debug

---
# For development in docker container
spring:
  profiles: docker
