server:
  port: 10001
  servlet:
    context-path: /ultrasound

spring:
  application:
    name: ultrasound-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/cubic
          jwk-set-uri: http://localhost:8083/auth/realms/cubic/protocol/openid-connect/certs

logging:
  level:
    ROOT: info
