server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ultrasound-api-service
          uri: lb://ultrasound-api-service
          predicates:
            - Path=/ultrasound/**
          filters:
            - RewritePath=/ultrasound/(?<path>.*), /$\{path}
        - id: chat-api-service
          uri: lb://chat-api-service
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat/(?<path>.*), /$\{path}

logging:
  level:
    ROOT: info

---
# For development in docker container
spring:
  profiles: docker
