server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ultrasound-api-service
          uri: lb://ultrasound-api-service/ultrasound
          predicates:
            - Path=/ultrasound/**
        - id: chat-api-service
          uri: lb://chat-api-service/chat
          predicates:
            - Path=/chat/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    ROOT: info
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
